name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Release Version
        id: get-version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.get-version.outputs.tag }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
          body: |
            version ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: success()
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        if: success()
        env:
          RELEASE_VERSION: ${{ steps.get-version.outputs.tag }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: siriuszg/cmak:${{ env.RELEASE_VERSION }},siriuszg/cmak:latest
